# Generated by Django 3.2.6 on 2021-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterField(
            model_name='animals',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='animals',
            name='weight',
            field=models.FloatField(),
        ),
    ]
