# Generated by Django 3.2.6 on 2021-08-16 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210816_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.family'),
        ),
    ]
